## This file is generated by the ConfigTableCSV plugin
class_name PropInfoData


var unique_id : int ##唯一id标识
var unique_name : String ##唯一字符串标识
var damage : float ##武器伤害
var is_melee_weapon : bool ##是否是近战武器1：是，0：不是
var pos_2d : Vector2 ##道具位置（不含高度）
var pos_3d : Vector3 ##道具位置（含高度）
var tags : Array[String] ##道具标签


func duplicate() -> PropInfoData:
	var data : PropInfoData = PropInfoData.new()
	data.unique_id = unique_id
	data.unique_name = unique_name
	data.damage = damage
	data.is_melee_weapon = is_melee_weapon
	data.pos_2d = pos_2d
	data.pos_3d = pos_3d
	data.tags = tags.duplicate(true)
	return data
